name: 'Lint'

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop', 'release']

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.x

      - name: Installs packages
        run: yarn --frozen-lockfile

      - name: Linting commit
        run: yarn lint:commit -- --to '${{ github.sha }}'

      - name: Linting check types
        run: yarn lint:check-types

      - name: Linting prettier
        run: yarn lint:prettier

      - name: Linting typescript
        run: yarn lint:typescript
